# vault-static-secret.yaml
# Defines which Vault secret to sync to a Kubernetes Secret
# VSO will automatically create and keep the K8s Secret in sync

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: myapp-config-sync
  namespace: vault-test
spec:
  # Reference the VaultAuth from the same namespace
  # Using local VaultAuth ensures ServiceAccount lookup works correctly
  vaultAuthRef: vault-auth

  # Type of Vault secret engine
  type: kv-v2

  # Mount path of the KV secrets engine
  mount: secret

  # Path to the secret within the mount
  # For KV-v2, this is the path without 'data/' prefix
  path: myapp/config

  # How often to refresh the secret from Vault
  # VSO will check for changes at this interval
  refreshAfter: 30s

  # Destination Kubernetes Secret configuration
  destination:
    # Name of the K8s Secret to create
    name: myapp-config

    # Create the secret if it doesn't exist
    create: true

    # Labels to add to the created Secret
    labels:
      app: myapp
      managed-by: vault-secrets-operator

    # Optional: Transformation to apply to secret data
    # transformation:
    #   excludeRaw: true
    #   templates:
    #     config.properties: |
    #       username={{ .Secrets.username }}
    #       password={{ .Secrets.password }}

  # Optional: Trigger pod rollout when secret changes
  # rolloutRestartTargets:
  #   - kind: Deployment
  #     name: myapp
